// Airline name mapping for common carriers
export const AIRLINE_NAMES: Record<string, string> = {
    "AA": "American Airlines",
    "DL": "Delta Air Lines",
    "UA": "United Airlines",
    "WN": "Southwest Airlines",
    "AS": "Alaska Airlines",
    "B6": "JetBlue Airways",
    "NK": "Spirit Airlines",
    "F9": "Frontier Airlines",
    "G4": "Allegiant Air",
    "SY": "Sun Country Airlines",

    // International
    "BA": "British Airways",
    "LH": "Lufthansa",
    "AF": "Air France",
    "KL": "KLM",
    "QR": "Qatar Airways",
    "EK": "Emirates",
    "EY": "Etihad Airways",
    "TK": "Turkish Airlines",
    "SQ": "Singapore Airlines",
    "CX": "Cathay Pacific",
    "QF": "Qantas",
    "AC": "Air Canada",
    "NH": "All Nippon Airways",
    "JL": "Japan Airlines",
    "KE": "Korean Air",
    "OZ": "Asiana Airlines",
    "AI": "Air India",
    "9W": "Jet Airways",
    "6E": "IndiGo",
    "SG": "SpiceJet",
    "UK": "Vistara",
    "RA": "Nepal Airlines",
    "H9": "Himalaya Airlines",
    "YT": "Yeti Airlines",
    "U4": "Buddha Air",

    // European
    "FR": "Ryanair",
    "U2": "easyJet",
    "VY": "Vueling",
    "IB": "Iberia",
    "AZ": "ITA Airways",
    "SK": "SAS",
    "AY": "Finnair",
    "LX": "Swiss",
    "OS": "Austrian Airlines",
    "SN": "Brussels Airlines",
    "TP": "TAP Air Portugal",
    "EI": "Aer Lingus",

    // Middle East & Asia
    "MS": "EgyptAir",
    "GF": "Gulf Air",
    "WY": "Oman Air",
    "SV": "Saudia",
    "RJ": "Royal Jordanian",
    "TG": "Thai Airways",
    "MH": "Malaysia Airlines",
    "GA": "Garuda Indonesia",
    "PR": "Philippine Airlines",
    "VN": "Vietnam Airlines",
    "CI": "China Airlines",
    "BR": "EVA Air",
    "CZ": "China Southern",
    "MU": "China Eastern",
    "CA": "Air China",
    "HU": "Hainan Airlines",
};

export function getAirlineName(code: string): string {
    return AIRLINE_NAMES[code] || code;
}
